-- ========================================================
-- RT Chocos: Products & Categories SQL Backup
-- Generated: 2026-09-28 19:41:53
-- Host: srv1875.hstgr.io | Database: u219698334_RTchocos
-- ========================================================

SET FOREIGN_KEY_CHECKS = 0;

-- Table structure for product_categories
CREATE TABLE IF NOT EXISTS `product_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for product_categories
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (1, 'Chocolates', 'chocolates', NULL, '2026-09-04 16:23:50', '2026-09-04 16:23:50') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (2, 'Bonbons', 'bonbons', NULL, '2026-09-04 16:23:50', '2026-09-04 16:23:50') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (3, 'Cacao', 'cacao', NULL, '2026-09-04 16:23:50', '2026-09-04 16:23:50') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (5, 'Gifting', 'gifting', NULL, '2026-09-04 16:23:51', '2026-09-04 16:23:51') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (6, 'Spreads', 'spreads', NULL, '2026-09-04 16:23:51', '2026-09-04 16:23:51') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (8, 'Vegan Truffles', 'vegan-truffles', '', '2026-09-04 16:28:46', '2026-09-04 16:28:46') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (9, 'Uncategorized', 'uncategorized', NULL, '2026-09-04 16:29:59', '2026-09-04 16:29:59') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (10, 'Spreads & Nut Butters', 'spreads-nut-butters', NULL, '2026-09-05 09:07:24', '2026-09-05 09:07:24') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (12, 'Ingredients', 'ingredients', NULL, '2026-09-05 09:07:24', '2026-09-05 09:07:24') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);
INSERT INTO `product_categories` (`id`, `name`, `slug`, `description`, `created_at`, `updated_at`) VALUES (13, 'Corporate & Gifting', 'corporate-gifting', NULL, '2026-09-05 09:07:24', '2026-09-05 09:07:24') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `slug`=VALUES(`slug`);

-- Table structure for products
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(150) NOT NULL,
  `name` varchar(255) NOT NULL,
  `short_description` text DEFAULT NULL,
  `long_description` longtext DEFAULT NULL,
  `price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `sale_price` decimal(10,2) DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `stock_quantity` int(11) NOT NULL DEFAULT 0,
  `image_main` varchar(255) DEFAULT NULL,
  `image_gallery` longtext DEFAULT NULL,
  `meta_title` varchar(255) DEFAULT NULL,
  `meta_description` text DEFAULT NULL,
  `meta_keywords` varchar(500) DEFAULT NULL,
  `is_featured` tinyint(1) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for products
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (6, 'almond-halwa-spread', 'Almond Halwa Spread', 'The richness of Indian almond halwa, reinvented into a clean, creamy and versatile spread made with minimal ingredients for pure, modern indulgence.', 'India’s beloved almond halwa, reinvented as a clean, luxurious spread.

Made with minimal, carefully chosen ingredients, this smooth and naturally nutty spread brings together the richness of almonds and the delicate warmth of cardamom without unnecessary additives. Clean-label, wholesome and crafted for modern indulgence, it is as versatile as it is delicious.

Spread it on toast, croissants and pancakes, swirl it into desserts, or use it to create bonbon fillings, chocolate confections and pastry creations.

A traditional favourite. A modern innovation. One irresistibly versatile jar.', 350.00, 299.00, 'Spreads & Nut Butters', 50, 'assets/products/prod-almond-halwa-spread-1790077418.png', '[]', 'Almond Halwa Spread | Clean Label | RT Chocos | Innovative recipe', 'Discover Almond Halwa Spread by RT Chocos—a creamy, nutty, clean-label indulgence made with minimal ingredients. Perfect for toast, desserts & bonbons.', 'almond halwa spread, almond spread, halwa spread, Indian almond spread, clean label spread, gourmet almond spread, almond spread India, RT Chocos, Innovative recipe, bestdiwaligifting, corporategifting,', 1, 1, '2026-09-05 09:07:25', '2026-09-22 11:43:38') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (7, 'cashew-coconut-spread', 'Cashew Coconut Spread', 'A silky-smooth blend of lightly roasted cashews and coconut, stone-ground in small batches for a rich, creamy texture. Clean, indulgent and endlessly versatile from toast and smoothies to desserts, pastries and bonbons.', 'A tropical indulgence, crafted in small batches.

Lightly roasted whole cashews and coconut are slowly stone-ground in small batches, creating an exceptionally silky, creamy texture with rich cashew notes and a delicate coconut finish. Made with minimal ingredients, with no palm oil or artificial preservatives.

Perfect on toast, croissants and fresh fruit, or elevate smoothie bowls, dessert frostings, cakes, pastries, bonbon fillings and chocolate creations.

Slow-crafted. Silky-smooth. Naturally indulgent.', 390.00, 360.00, 'Spreads & Nut Butters', 45, 'assets/products/prod-cashew-coconut-spread-1790015793.png', '[]', 'Cashew Coconut Spread | Innovative  Recipe | Gourmet Diwali & Corporate Gifts', 'Discover RT Chocos Cashew Coconut Spread, stone-ground in small batches for a silky texture. Perfect for toast, desserts, bonbons, Diwali & corporate gifting.', 'cashew coconut spread, cashew spread, cashew butter, coconut spread, gourmet nut butter, clean label spread, premium Diwali gifts, Diwali gifting, corporate gifting, corporate gifts India, gourmet gifting, premium food gifts, RT Chocos', 1, 1, '2026-09-05 09:07:25', '2026-09-21 18:36:33') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (9, 'almond-spread', 'Crunchy Almond Spread', 'A clean-label, minimally processed almond spread, stone-ground in small batches from premium almonds for a rich, creamy texture and irresistible crunch. Perfect for everyday indulgence, desserts, bonbons, and premium Diwali & corporate gifting.', 'Pure almond indulgence, crafted with a delicious crunch. Made from premium almonds and minimal ingredients, this clean-label, minimally processed spread is stone-ground and crafted in small batches for exceptional creaminess with an irresistible almond crunch.

Perfect for toast, croissants, desserts, pastries and bonbons and beautifully suited for premium Diwali and corporate gifting.

Clean. Crafted. Crunchy. Unmistakably indulgent.', 360.00, 325.00, 'Spreads & Nut Butters', 70, 'assets/products/prod-almond-spread-1790015745.png', '[]', 'Crunchy Almond Spread | Premium Nut Butter | RT Chocos', 'RT Chocos Crunchy Almond Spread ,premium almonds, stone-ground in small batches for creamy richness and crunch. A perfect choice for Diwali & corporate gifting.', 'crunchy almond spread, almond spread, almond butter, premium almond spread, almond spread India, clean label spread, stone ground almond spread, gourmet nut butter, Diwali gifting, Diwali gifts, Diwali corporate gifting, corporate gifting, corporate gifts India, premium corporate gifts, gourmet Diwali gifts, festive gifting, premium food gifts, RT Chocos', 1, 1, '2026-09-05 09:07:25', '2026-09-21 18:35:45') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (14, 'dates-powder', 'Dates Powder', 'Natural dates transformed into a versatile powder with rich, caramel-like notes.', '100% premium sun-ripened dates, dehydrated and micro-milled into a fine, nutrient-rich natural sweetener. A diabetic-friendly, high-fiber substitute for refined sugar.', 250.00, 220.00, 'Ingredients', 90, 'assets/products/dates_powder.jpg', NULL, NULL, NULL, NULL, 1, 1, '2026-09-05 09:07:25', '2026-09-05 09:07:25') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (15, 'handcrafted-chocolates', 'Handcrafted Chocolates', 'Artisan chocolates designed for celebrations, gifting and special occasions.', 'A curated box of 12 hand-painted ganache and praline bonbons. Flavours include Salted Caramel, Hazelnut Gianduja, Dark Espresso, and Cardamom Truffle.', 850.00, 799.00, 'Corporate & Gifting', 35, 'assets/products/handcrafted_chocolates.jpg', NULL, NULL, NULL, NULL, 1, 1, '2026-09-05 09:07:26', '2026-09-05 09:07:26') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (17, 'customized-chocolate-inclusion-bar', 'Customized Chocolate Inclusion Bar', 'raft your own chocolate experience. Our Customized Inclusion Bars combine fine chocolate with your choice of nuts, fruits, spices, seeds and other real ingredients crafted to your taste, occasion and vision.', 'Chocolate, made your way. Create a bespoke inclusion bar with fine chocolate and carefully selected ingredients of your choice. From nuts and dried fruits to seeds, spices and unique inclusions, every bar is crafted to make your idea deliciously distinctive.', 180.00, 150.00, 'Chocolates', 50, 'assets/products/custom_branding_showcase.jpg', '[]', 'Customized Chocolate Inclusion Bar | RT Chocos', 'Choose from a wide range of nuts, fruits, seeds, spices and other real ingredients to create a bespoke inclusion bar, crafted with fine chocolate and RT Chocos\' chocolate expertise.', 'customized chocolate bar, custom chocolate bar, chocolate inclusion bar, customized chocolate, personalized chocolate bar, inclusion chocolate, custom chocolate India, artisan chocolate India, custom chocolate gifting, corporate chocolate gifting', 0, 1, '2026-09-14 18:14:09', '2026-09-15 19:29:32') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (18, 'hazelnut-spread-clean-label-product-healthy-gifting', 'Hazelnut Spread | Clean Label product | Healthy Gifting', 'Luxuriously roasted hazelnuts, stone-ground to velvety perfection. Rich, refined and irresistibly smooth made for spreading, creating and gifting.', 'A rich, velvety spread with the unmistakable warmth of roasted hazelnuts and a beautifully lingering finish. Made with premium ingredients, minimal processing and small-batch stone grinding for an exceptionally smooth mouthfeel.

Sublime on toast and croissants, decadent in cakes, pastries, ice cream and desserts, and effortlessly indulgent in bonbons, pralines and chocolate fillings.

A little jar of hazelnut luxury made for spreading, creating and gifting.', 350.00, 299.00, 'Spreads', 50, 'assets/products/prod-hazelnut-spread-clean-label-product-healthy-gifting-1790015567.png', '[]', 'Hazelnut Spread | Premium Diwali & Corporate Gifting | RT Chocos', 'Discover RT Chocos Hazelnut Spread premium roasted hazelnuts, stone-ground in small batches for silky richness. Perfect for desserts, bonbons, Diwali & corporate gifting.', 'hazelnut spread, hazelnut butter, premium hazelnut spread, hazelnut spread India, gourmet hazelnut spread, clean label hazelnut spread, stone ground hazelnut spread, premium nut butter, Diwali gifting, Diwali gifts, corporate gifting, corporate gifts India, premium corporate gifts, gourmet gifting, premium food gifts, RT Chocos', 0, 1, '2026-09-14 18:36:32', '2026-09-21 18:32:47') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (19, 'gourmet-stuffed-dates-gift-box', 'Gourmet Stuffed Dates Gift Box', 'Plump, naturally sweet dates handcrafted with indulgent fillings and premium nuts-an elegant, wholesome treat made for festive celebrations and thoughtful gifting.', 'A little box of natural sweetness, beautifully handcrafted.

Premium dates are carefully selected, delicately stuffed and finished with an assortment of premium nuts and artisanal toppings, creating a luxurious bite with contrasting textures and flavours. Naturally rich and satisfying, each piece brings together the deep caramel-like sweetness of dates with the richness and crunch of carefully chosen ingredients.

Beautifully presented in an elegant gift box, it makes a sophisticated choice for Diwali gifting, corporate gifting, festive hampers and premium celebrations.

Enjoy them as an indulgent snack, serve alongside coffee or tea, or add them to dessert platters and festive spreads.

Naturally indulgent. Handcrafted with care. Made to be gifted.', 500.00, 450.00, 'Chocolates', 50, 'assets/products/prod-gourmet-stuffed-dates-gift-box-1790015134.png', '[]', 'Gourmet Stuffed Dates | Diwali & Corporate Gifting | RT Chocos  SEO Meta Description', 'Discover premium stuffed dates crafted with indulgent fillings and nuts. An elegant choice for Diwali gifting, corporate gifts, festive hampers and celebrations.', 'stuffed dates, gourmet stuffed dates, stuffed dates gift box, premium dates gift box, stuffed dates India, gourmet dates, luxury dates gift, Diwali gifting, Diwali gifts, Diwali gift hampers, corporate gifting, corporate gifts India, premium corporate gifts, gourmet gifting, festive gifting, premium food gifts, luxury gifting, RT Chocos', 0, 1, '2026-09-14 18:40:26', '2026-09-21 18:25:34') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (20, 'the-rocher-collection', 'The Rocher Collection', 'Handcrafted chocolate Rochers in two irresistible creations Almond and Mixed Fruit made for indulgence, celebration and elegant gifting.', 'The Rocher Collection brings together two handcrafted favourites Almond Rocher with roasted almonds and Mixed Fruit Rocher with a delightful blend of fruits and nuts, all enveloped in rich chocolate.

Made in small batches with premium ingredients, these elegant Rochers are perfect for festive celebrations, sharing and premium Diwali & corporate gifting.', 300.00, 250.00, 'Chocolates', 50, 'assets/products/prod-the-rocher-collection-1790015004.png', '[]', 'Rocher Chocolate Collection | Diwali & Corporate Gifting', 'Discover RT Chocos Rocher Collection handcrafted Almond & Mixed Fruit Rochers made with premium ingredients. Perfect for Diwali gifting, corporate gifts & celebrations.', 'rocher chocolate, chocolate rocher, rocher collection, almond rocher, mixed fruit rocher, premium chocolates, gourmet chocolate gifting, chocolate gift box, Diwali gifting, Diwali gifts, Diwali chocolate gifts, corporate gifting, corporate gifts India, premium corporate gifts, corporate chocolate gifts, festive gifting, luxury chocolate gifts, RT Chocos', 0, 1, '2026-09-15 10:54:08', '2026-09-21 18:23:24') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (21, 'almond-bark', 'Almond Bark', 'Premium chocolate meets generously roasted almonds in this elegant, indulgent bark—rich, crisp and irresistibly satisfying. Perfect for gifting, sharing, or elevating your festive celebrations.', 'A beautifully crafted chocolate bark studded generously with premium roasted almonds, bringing together the smoothness of fine chocolate and the irresistible crunch of perfectly roasted nuts. Each bite offers a delicious contrast of silky chocolate, deep roasted flavour and satisfying texture.

Perfect for gifting, festive indulgence and everyday chocolate cravings—a thoughtful addition to Diwali hampers and premium corporate gifting.', 420.00, 390.00, 'Chocolates', 100, 'assets/products/prod-almond-bark-1790015356.png', '[]', 'Almond Bark Chocolate | Diwali & Corporate Gifting | RT Chocos', 'Discover RT Chocos Almond Bark—premium chocolate generously layered with roasted almonds for a rich, satisfying crunch. Perfect for Diwali & corporate gifting.', 'almond bark, almond bark chocolate, chocolate almond bark, premium almond chocolate, almond chocolate India, gourmet chocolate, premium chocolates India, Diwali gifting, Diwali gifts, corporate gifting, corporate gifts India, premium corporate gifts, chocolate gifting, gourmet Diwali gifts, festive chocolate gifts, premium food gifts, RT Chocos', 1, 1, '2026-09-15 19:31:02', '2026-09-21 18:29:16') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);
INSERT INTO `products` (`id`, `slug`, `name`, `short_description`, `long_description`, `price`, `sale_price`, `category`, `stock_quantity`, `image_main`, `image_gallery`, `meta_title`, `meta_description`, `meta_keywords`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES (25, 'classic-almond-spread', 'Classic Almond Butter Spread', 'Classic, creamy and crafted around the richness of premium slow-roasted almonds.', 'Stone-ground for 24 hours to achieve an ultra-smooth, creamy texture. Made solely with high-grade California almonds and a touch of sea salt. Free from hydrogenated oils and artificial preservatives.', 350.00, 325.00, 'Spreads & Nut Butters', 100, 'assets/products/prod-classic-almond-spread-1790078880.png', '[]', 'Classic Almond Spread | Premium Nut Butter | RT Chocos', 'Discover RT Chocos Classic Almond Spread made with premium almonds and minimal ingredients for rich, creamy indulgence. Perfect for toast, desserts & gifting.', 'classic almond spread, almond spread, almond butter, premium almond spread, almond butter India, gourmet almond spread, clean label almond spread, premium nut butter, almond spread India, Diwali gifting, Diwali gifts, corporate gifting, corporate gifts India, premium corporate gifts, gourmet gifting, RT Chocos', 0, 1, '2026-09-15 19:31:02', '2026-09-22 12:08:00') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `short_description`=VALUES(`short_description`), `long_description`=VALUES(`long_description`), `price`=VALUES(`price`), `sale_price`=VALUES(`sale_price`), `stock_quantity`=VALUES(`stock_quantity`), `image_main`=VALUES(`image_main`), `meta_title`=VALUES(`meta_title`), `meta_description`=VALUES(`meta_description`);

SET FOREIGN_KEY_CHECKS = 1;
